// Code generated by protoc-gen-go. DO NOT EDIT.
// source: editor.proto

package editorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppUserInfo struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Gender               int32    `protobuf:"varint,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Age                  int32    `protobuf:"varint,7,opt,name=Age,proto3" json:"Age,omitempty"`
	Avatar               string   `protobuf:"bytes,8,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	BgImg                string   `protobuf:"bytes,9,opt,name=BgImg,proto3" json:"BgImg,omitempty"`
	Signature            string   `protobuf:"bytes,10,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Birthday             string   `protobuf:"bytes,11,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	Nation               string   `protobuf:"bytes,12,opt,name=Nation,proto3" json:"Nation,omitempty"`
	Province             string   `protobuf:"bytes,13,opt,name=Province,proto3" json:"Province,omitempty"`
	City                 string   `protobuf:"bytes,14,opt,name=City,proto3" json:"City,omitempty"`
	County               string   `protobuf:"bytes,15,opt,name=County,proto3" json:"County,omitempty"`
	Location             string   `protobuf:"bytes,16,opt,name=Location,proto3" json:"Location,omitempty"`
	RegIP                int32    `protobuf:"varint,17,opt,name=RegIP,proto3" json:"RegIP,omitempty"`
	Created              int32    `protobuf:"varint,18,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated              int32    `protobuf:"varint,19,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppUserInfo) Reset()         { *m = AppUserInfo{} }
func (m *AppUserInfo) String() string { return proto.CompactTextString(m) }
func (*AppUserInfo) ProtoMessage()    {}
func (*AppUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{0}
}

func (m *AppUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppUserInfo.Unmarshal(m, b)
}
func (m *AppUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppUserInfo.Marshal(b, m, deterministic)
}
func (m *AppUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppUserInfo.Merge(m, src)
}
func (m *AppUserInfo) XXX_Size() int {
	return xxx_messageInfo_AppUserInfo.Size(m)
}
func (m *AppUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AppUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AppUserInfo proto.InternalMessageInfo

func (m *AppUserInfo) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AppUserInfo) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AppUserInfo) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *AppUserInfo) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AppUserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AppUserInfo) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *AppUserInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *AppUserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AppUserInfo) GetBgImg() string {
	if m != nil {
		return m.BgImg
	}
	return ""
}

func (m *AppUserInfo) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *AppUserInfo) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *AppUserInfo) GetNation() string {
	if m != nil {
		return m.Nation
	}
	return ""
}

func (m *AppUserInfo) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *AppUserInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AppUserInfo) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *AppUserInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *AppUserInfo) GetRegIP() int32 {
	if m != nil {
		return m.RegIP
	}
	return 0
}

func (m *AppUserInfo) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AppUserInfo) GetUpdated() int32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type EditProfileReq struct {
	Uid                  int64        `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Fields               []string     `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	Profile              *AppUserInfo `protobuf:"bytes,3,opt,name=Profile,proto3" json:"Profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EditProfileReq) Reset()         { *m = EditProfileReq{} }
func (m *EditProfileReq) String() string { return proto.CompactTextString(m) }
func (*EditProfileReq) ProtoMessage()    {}
func (*EditProfileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{1}
}

func (m *EditProfileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileReq.Unmarshal(m, b)
}
func (m *EditProfileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileReq.Marshal(b, m, deterministic)
}
func (m *EditProfileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileReq.Merge(m, src)
}
func (m *EditProfileReq) XXX_Size() int {
	return xxx_messageInfo_EditProfileReq.Size(m)
}
func (m *EditProfileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileReq proto.InternalMessageInfo

func (m *EditProfileReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *EditProfileReq) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *EditProfileReq) GetProfile() *AppUserInfo {
	if m != nil {
		return m.Profile
	}
	return nil
}

type EditProfileRes struct {
	Err                  string   `protobuf:"bytes,1,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileRes) Reset()         { *m = EditProfileRes{} }
func (m *EditProfileRes) String() string { return proto.CompactTextString(m) }
func (*EditProfileRes) ProtoMessage()    {}
func (*EditProfileRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{2}
}

func (m *EditProfileRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileRes.Unmarshal(m, b)
}
func (m *EditProfileRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileRes.Marshal(b, m, deterministic)
}
func (m *EditProfileRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileRes.Merge(m, src)
}
func (m *EditProfileRes) XXX_Size() int {
	return xxx_messageInfo_EditProfileRes.Size(m)
}
func (m *EditProfileRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileRes.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileRes proto.InternalMessageInfo

func (m *EditProfileRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type AppEditorCharacter struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	BookId               int64    `protobuf:"varint,2,opt,name=BookId,proto3" json:"BookId,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	CharacterType        int32    `protobuf:"varint,4,opt,name=CharacterType,proto3" json:"CharacterType,omitempty"`
	Align                string   `protobuf:"bytes,5,opt,name=Align,proto3" json:"Align,omitempty"`
	Icon                 string   `protobuf:"bytes,6,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Created              int32    `protobuf:"varint,7,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated              int32    `protobuf:"varint,8,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppEditorCharacter) Reset()         { *m = AppEditorCharacter{} }
func (m *AppEditorCharacter) String() string { return proto.CompactTextString(m) }
func (*AppEditorCharacter) ProtoMessage()    {}
func (*AppEditorCharacter) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{3}
}

func (m *AppEditorCharacter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppEditorCharacter.Unmarshal(m, b)
}
func (m *AppEditorCharacter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppEditorCharacter.Marshal(b, m, deterministic)
}
func (m *AppEditorCharacter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppEditorCharacter.Merge(m, src)
}
func (m *AppEditorCharacter) XXX_Size() int {
	return xxx_messageInfo_AppEditorCharacter.Size(m)
}
func (m *AppEditorCharacter) XXX_DiscardUnknown() {
	xxx_messageInfo_AppEditorCharacter.DiscardUnknown(m)
}

var xxx_messageInfo_AppEditorCharacter proto.InternalMessageInfo

func (m *AppEditorCharacter) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AppEditorCharacter) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *AppEditorCharacter) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *AppEditorCharacter) GetCharacterType() int32 {
	if m != nil {
		return m.CharacterType
	}
	return 0
}

func (m *AppEditorCharacter) GetAlign() string {
	if m != nil {
		return m.Align
	}
	return ""
}

func (m *AppEditorCharacter) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *AppEditorCharacter) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AppEditorCharacter) GetUpdated() int32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type AppEditorBook struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BookID               int64    `protobuf:"varint,3,opt,name=BookID,proto3" json:"BookID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Desc                 string   `protobuf:"bytes,5,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Images               string   `protobuf:"bytes,6,opt,name=Images,proto3" json:"Images,omitempty"`
	OnlineStatus         int32    `protobuf:"varint,7,opt,name=OnlineStatus,proto3" json:"OnlineStatus,omitempty"`
	WorkStatus           int32    `protobuf:"varint,8,opt,name=WorkStatus,proto3" json:"WorkStatus,omitempty"`
	AuthorNum            int32    `protobuf:"varint,9,opt,name=AuthorNum,proto3" json:"AuthorNum,omitempty"`
	Created              int32    `protobuf:"varint,10,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated              int32    `protobuf:"varint,11,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppEditorBook) Reset()         { *m = AppEditorBook{} }
func (m *AppEditorBook) String() string { return proto.CompactTextString(m) }
func (*AppEditorBook) ProtoMessage()    {}
func (*AppEditorBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{4}
}

func (m *AppEditorBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppEditorBook.Unmarshal(m, b)
}
func (m *AppEditorBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppEditorBook.Marshal(b, m, deterministic)
}
func (m *AppEditorBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppEditorBook.Merge(m, src)
}
func (m *AppEditorBook) XXX_Size() int {
	return xxx_messageInfo_AppEditorBook.Size(m)
}
func (m *AppEditorBook) XXX_DiscardUnknown() {
	xxx_messageInfo_AppEditorBook.DiscardUnknown(m)
}

var xxx_messageInfo_AppEditorBook proto.InternalMessageInfo

func (m *AppEditorBook) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AppEditorBook) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AppEditorBook) GetBookID() int64 {
	if m != nil {
		return m.BookID
	}
	return 0
}

func (m *AppEditorBook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppEditorBook) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *AppEditorBook) GetImages() string {
	if m != nil {
		return m.Images
	}
	return ""
}

func (m *AppEditorBook) GetOnlineStatus() int32 {
	if m != nil {
		return m.OnlineStatus
	}
	return 0
}

func (m *AppEditorBook) GetWorkStatus() int32 {
	if m != nil {
		return m.WorkStatus
	}
	return 0
}

func (m *AppEditorBook) GetAuthorNum() int32 {
	if m != nil {
		return m.AuthorNum
	}
	return 0
}

func (m *AppEditorBook) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AppEditorBook) GetUpdated() int32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type AppEditorChapter struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BookID               int64    `protobuf:"varint,2,opt,name=BookID,proto3" json:"BookID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	CmdCount             int32    `protobuf:"varint,4,opt,name=CmdCount,proto3" json:"CmdCount,omitempty"`
	WordsCount           int32    `protobuf:"varint,5,opt,name=WordsCount,proto3" json:"WordsCount,omitempty"`
	OnlineStatus         int32    `protobuf:"varint,6,opt,name=OnlineStatus,proto3" json:"OnlineStatus,omitempty"`
	Created              int32    `protobuf:"varint,7,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated              int32    `protobuf:"varint,8,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppEditorChapter) Reset()         { *m = AppEditorChapter{} }
func (m *AppEditorChapter) String() string { return proto.CompactTextString(m) }
func (*AppEditorChapter) ProtoMessage()    {}
func (*AppEditorChapter) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{5}
}

func (m *AppEditorChapter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppEditorChapter.Unmarshal(m, b)
}
func (m *AppEditorChapter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppEditorChapter.Marshal(b, m, deterministic)
}
func (m *AppEditorChapter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppEditorChapter.Merge(m, src)
}
func (m *AppEditorChapter) XXX_Size() int {
	return xxx_messageInfo_AppEditorChapter.Size(m)
}
func (m *AppEditorChapter) XXX_DiscardUnknown() {
	xxx_messageInfo_AppEditorChapter.DiscardUnknown(m)
}

var xxx_messageInfo_AppEditorChapter proto.InternalMessageInfo

func (m *AppEditorChapter) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AppEditorChapter) GetBookID() int64 {
	if m != nil {
		return m.BookID
	}
	return 0
}

func (m *AppEditorChapter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppEditorChapter) GetCmdCount() int32 {
	if m != nil {
		return m.CmdCount
	}
	return 0
}

func (m *AppEditorChapter) GetWordsCount() int32 {
	if m != nil {
		return m.WordsCount
	}
	return 0
}

func (m *AppEditorChapter) GetOnlineStatus() int32 {
	if m != nil {
		return m.OnlineStatus
	}
	return 0
}

func (m *AppEditorChapter) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AppEditorChapter) GetUpdated() int32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type EditorBook struct {
	Book                 *AppEditorBook      `protobuf:"bytes,1,opt,name=Book,proto3" json:"Book,omitempty"`
	Chapters             []*AppEditorChapter `protobuf:"bytes,2,rep,name=Chapters,proto3" json:"Chapters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *EditorBook) Reset()         { *m = EditorBook{} }
func (m *EditorBook) String() string { return proto.CompactTextString(m) }
func (*EditorBook) ProtoMessage()    {}
func (*EditorBook) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{6}
}

func (m *EditorBook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditorBook.Unmarshal(m, b)
}
func (m *EditorBook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditorBook.Marshal(b, m, deterministic)
}
func (m *EditorBook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditorBook.Merge(m, src)
}
func (m *EditorBook) XXX_Size() int {
	return xxx_messageInfo_EditorBook.Size(m)
}
func (m *EditorBook) XXX_DiscardUnknown() {
	xxx_messageInfo_EditorBook.DiscardUnknown(m)
}

var xxx_messageInfo_EditorBook proto.InternalMessageInfo

func (m *EditorBook) GetBook() *AppEditorBook {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *EditorBook) GetChapters() []*AppEditorChapter {
	if m != nil {
		return m.Chapters
	}
	return nil
}

type AppEditorCmd struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	BookID               int64    `protobuf:"varint,2,opt,name=BookID,proto3" json:"BookID,omitempty"`
	UserID               int64    `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	ChapterID            int32    `protobuf:"varint,4,opt,name=ChapterID,proto3" json:"ChapterID,omitempty"`
	CmdList              string   `protobuf:"bytes,5,opt,name=CmdList,proto3" json:"CmdList,omitempty"`
	Created              int32    `protobuf:"varint,6,opt,name=Created,proto3" json:"Created,omitempty"`
	Updated              int32    `protobuf:"varint,7,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppEditorCmd) Reset()         { *m = AppEditorCmd{} }
func (m *AppEditorCmd) String() string { return proto.CompactTextString(m) }
func (*AppEditorCmd) ProtoMessage()    {}
func (*AppEditorCmd) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{7}
}

func (m *AppEditorCmd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppEditorCmd.Unmarshal(m, b)
}
func (m *AppEditorCmd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppEditorCmd.Marshal(b, m, deterministic)
}
func (m *AppEditorCmd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppEditorCmd.Merge(m, src)
}
func (m *AppEditorCmd) XXX_Size() int {
	return xxx_messageInfo_AppEditorCmd.Size(m)
}
func (m *AppEditorCmd) XXX_DiscardUnknown() {
	xxx_messageInfo_AppEditorCmd.DiscardUnknown(m)
}

var xxx_messageInfo_AppEditorCmd proto.InternalMessageInfo

func (m *AppEditorCmd) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AppEditorCmd) GetBookID() int64 {
	if m != nil {
		return m.BookID
	}
	return 0
}

func (m *AppEditorCmd) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AppEditorCmd) GetChapterID() int32 {
	if m != nil {
		return m.ChapterID
	}
	return 0
}

func (m *AppEditorCmd) GetCmdList() string {
	if m != nil {
		return m.CmdList
	}
	return ""
}

func (m *AppEditorCmd) GetCreated() int32 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AppEditorCmd) GetUpdated() int32 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type CharactersReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CharactersReq) Reset()         { *m = CharactersReq{} }
func (m *CharactersReq) String() string { return proto.CompactTextString(m) }
func (*CharactersReq) ProtoMessage()    {}
func (*CharactersReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{8}
}

func (m *CharactersReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharactersReq.Unmarshal(m, b)
}
func (m *CharactersReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharactersReq.Marshal(b, m, deterministic)
}
func (m *CharactersReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharactersReq.Merge(m, src)
}
func (m *CharactersReq) XXX_Size() int {
	return xxx_messageInfo_CharactersReq.Size(m)
}
func (m *CharactersReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CharactersReq.DiscardUnknown(m)
}

var xxx_messageInfo_CharactersReq proto.InternalMessageInfo

func (m *CharactersReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type CharactersRes struct {
	Data                 []*AppEditorCharacter `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Err                  string                `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CharactersRes) Reset()         { *m = CharactersRes{} }
func (m *CharactersRes) String() string { return proto.CompactTextString(m) }
func (*CharactersRes) ProtoMessage()    {}
func (*CharactersRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{9}
}

func (m *CharactersRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CharactersRes.Unmarshal(m, b)
}
func (m *CharactersRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CharactersRes.Marshal(b, m, deterministic)
}
func (m *CharactersRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CharactersRes.Merge(m, src)
}
func (m *CharactersRes) XXX_Size() int {
	return xxx_messageInfo_CharactersRes.Size(m)
}
func (m *CharactersRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CharactersRes.DiscardUnknown(m)
}

var xxx_messageInfo_CharactersRes proto.InternalMessageInfo

func (m *CharactersRes) GetData() []*AppEditorCharacter {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CharactersRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type AddCharacterReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Align                string   `protobuf:"bytes,4,opt,name=Align,proto3" json:"Align,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCharacterReq) Reset()         { *m = AddCharacterReq{} }
func (m *AddCharacterReq) String() string { return proto.CompactTextString(m) }
func (*AddCharacterReq) ProtoMessage()    {}
func (*AddCharacterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{10}
}

func (m *AddCharacterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCharacterReq.Unmarshal(m, b)
}
func (m *AddCharacterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCharacterReq.Marshal(b, m, deterministic)
}
func (m *AddCharacterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCharacterReq.Merge(m, src)
}
func (m *AddCharacterReq) XXX_Size() int {
	return xxx_messageInfo_AddCharacterReq.Size(m)
}
func (m *AddCharacterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCharacterReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddCharacterReq proto.InternalMessageInfo

func (m *AddCharacterReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *AddCharacterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddCharacterReq) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *AddCharacterReq) GetAlign() string {
	if m != nil {
		return m.Align
	}
	return ""
}

type AddCharacterRes struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Err                  string   `protobuf:"bytes,15,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddCharacterRes) Reset()         { *m = AddCharacterRes{} }
func (m *AddCharacterRes) String() string { return proto.CompactTextString(m) }
func (*AddCharacterRes) ProtoMessage()    {}
func (*AddCharacterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{11}
}

func (m *AddCharacterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddCharacterRes.Unmarshal(m, b)
}
func (m *AddCharacterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddCharacterRes.Marshal(b, m, deterministic)
}
func (m *AddCharacterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddCharacterRes.Merge(m, src)
}
func (m *AddCharacterRes) XXX_Size() int {
	return xxx_messageInfo_AddCharacterRes.Size(m)
}
func (m *AddCharacterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddCharacterRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddCharacterRes proto.InternalMessageInfo

func (m *AddCharacterRes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddCharacterRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type DelCharacterReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	CharacterId          int32    `protobuf:"varint,2,opt,name=CharacterId,proto3" json:"CharacterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCharacterReq) Reset()         { *m = DelCharacterReq{} }
func (m *DelCharacterReq) String() string { return proto.CompactTextString(m) }
func (*DelCharacterReq) ProtoMessage()    {}
func (*DelCharacterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{12}
}

func (m *DelCharacterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCharacterReq.Unmarshal(m, b)
}
func (m *DelCharacterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCharacterReq.Marshal(b, m, deterministic)
}
func (m *DelCharacterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCharacterReq.Merge(m, src)
}
func (m *DelCharacterReq) XXX_Size() int {
	return xxx_messageInfo_DelCharacterReq.Size(m)
}
func (m *DelCharacterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCharacterReq.DiscardUnknown(m)
}

var xxx_messageInfo_DelCharacterReq proto.InternalMessageInfo

func (m *DelCharacterReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *DelCharacterReq) GetCharacterId() int32 {
	if m != nil {
		return m.CharacterId
	}
	return 0
}

type DelCharacterRes struct {
	Err                  string   `protobuf:"bytes,15,opt,name=Err,proto3" json:"Err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelCharacterRes) Reset()         { *m = DelCharacterRes{} }
func (m *DelCharacterRes) String() string { return proto.CompactTextString(m) }
func (*DelCharacterRes) ProtoMessage()    {}
func (*DelCharacterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{13}
}

func (m *DelCharacterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelCharacterRes.Unmarshal(m, b)
}
func (m *DelCharacterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelCharacterRes.Marshal(b, m, deterministic)
}
func (m *DelCharacterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelCharacterRes.Merge(m, src)
}
func (m *DelCharacterRes) XXX_Size() int {
	return xxx_messageInfo_DelCharacterRes.Size(m)
}
func (m *DelCharacterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DelCharacterRes.DiscardUnknown(m)
}

var xxx_messageInfo_DelCharacterRes proto.InternalMessageInfo

func (m *DelCharacterRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type EditCharacterReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	CharacterId          int32    `protobuf:"varint,2,opt,name=characterId,proto3" json:"characterId,omitempty"`
	Field                string   `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditCharacterReq) Reset()         { *m = EditCharacterReq{} }
func (m *EditCharacterReq) String() string { return proto.CompactTextString(m) }
func (*EditCharacterReq) ProtoMessage()    {}
func (*EditCharacterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{14}
}

func (m *EditCharacterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCharacterReq.Unmarshal(m, b)
}
func (m *EditCharacterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCharacterReq.Marshal(b, m, deterministic)
}
func (m *EditCharacterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCharacterReq.Merge(m, src)
}
func (m *EditCharacterReq) XXX_Size() int {
	return xxx_messageInfo_EditCharacterReq.Size(m)
}
func (m *EditCharacterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCharacterReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditCharacterReq proto.InternalMessageInfo

func (m *EditCharacterReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *EditCharacterReq) GetCharacterId() int32 {
	if m != nil {
		return m.CharacterId
	}
	return 0
}

func (m *EditCharacterReq) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *EditCharacterReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EditCharacterRes struct {
	Err                  string   `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditCharacterRes) Reset()         { *m = EditCharacterRes{} }
func (m *EditCharacterRes) String() string { return proto.CompactTextString(m) }
func (*EditCharacterRes) ProtoMessage()    {}
func (*EditCharacterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{15}
}

func (m *EditCharacterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditCharacterRes.Unmarshal(m, b)
}
func (m *EditCharacterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditCharacterRes.Marshal(b, m, deterministic)
}
func (m *EditCharacterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditCharacterRes.Merge(m, src)
}
func (m *EditCharacterRes) XXX_Size() int {
	return xxx_messageInfo_EditCharacterRes.Size(m)
}
func (m *EditCharacterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EditCharacterRes.DiscardUnknown(m)
}

var xxx_messageInfo_EditCharacterRes proto.InternalMessageInfo

func (m *EditCharacterRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetBookByIdReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookByIdReq) Reset()         { *m = GetBookByIdReq{} }
func (m *GetBookByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetBookByIdReq) ProtoMessage()    {}
func (*GetBookByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{16}
}

func (m *GetBookByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookByIdReq.Unmarshal(m, b)
}
func (m *GetBookByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookByIdReq.Marshal(b, m, deterministic)
}
func (m *GetBookByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookByIdReq.Merge(m, src)
}
func (m *GetBookByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetBookByIdReq.Size(m)
}
func (m *GetBookByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookByIdReq proto.InternalMessageInfo

func (m *GetBookByIdReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type GetBookByIdRes struct {
	Book                 *AppEditorBook `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Err                  string         `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetBookByIdRes) Reset()         { *m = GetBookByIdRes{} }
func (m *GetBookByIdRes) String() string { return proto.CompactTextString(m) }
func (*GetBookByIdRes) ProtoMessage()    {}
func (*GetBookByIdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{17}
}

func (m *GetBookByIdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookByIdRes.Unmarshal(m, b)
}
func (m *GetBookByIdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookByIdRes.Marshal(b, m, deterministic)
}
func (m *GetBookByIdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookByIdRes.Merge(m, src)
}
func (m *GetBookByIdRes) XXX_Size() int {
	return xxx_messageInfo_GetBookByIdRes.Size(m)
}
func (m *GetBookByIdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookByIdRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookByIdRes proto.InternalMessageInfo

func (m *GetBookByIdRes) GetBook() *AppEditorBook {
	if m != nil {
		return m.Book
	}
	return nil
}

func (m *GetBookByIdRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetChaptersByIdReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetChaptersByIdReq) Reset()         { *m = GetChaptersByIdReq{} }
func (m *GetChaptersByIdReq) String() string { return proto.CompactTextString(m) }
func (*GetChaptersByIdReq) ProtoMessage()    {}
func (*GetChaptersByIdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{18}
}

func (m *GetChaptersByIdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChaptersByIdReq.Unmarshal(m, b)
}
func (m *GetChaptersByIdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChaptersByIdReq.Marshal(b, m, deterministic)
}
func (m *GetChaptersByIdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChaptersByIdReq.Merge(m, src)
}
func (m *GetChaptersByIdReq) XXX_Size() int {
	return xxx_messageInfo_GetChaptersByIdReq.Size(m)
}
func (m *GetChaptersByIdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChaptersByIdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetChaptersByIdReq proto.InternalMessageInfo

func (m *GetChaptersByIdReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type GetChaptersByIdRes struct {
	Chapters             []*AppEditorChapter `protobuf:"bytes,1,rep,name=chapters,proto3" json:"chapters,omitempty"`
	Err                  string              `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetChaptersByIdRes) Reset()         { *m = GetChaptersByIdRes{} }
func (m *GetChaptersByIdRes) String() string { return proto.CompactTextString(m) }
func (*GetChaptersByIdRes) ProtoMessage()    {}
func (*GetChaptersByIdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{19}
}

func (m *GetChaptersByIdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetChaptersByIdRes.Unmarshal(m, b)
}
func (m *GetChaptersByIdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetChaptersByIdRes.Marshal(b, m, deterministic)
}
func (m *GetChaptersByIdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetChaptersByIdRes.Merge(m, src)
}
func (m *GetChaptersByIdRes) XXX_Size() int {
	return xxx_messageInfo_GetChaptersByIdRes.Size(m)
}
func (m *GetChaptersByIdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetChaptersByIdRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetChaptersByIdRes proto.InternalMessageInfo

func (m *GetChaptersByIdRes) GetChapters() []*AppEditorChapter {
	if m != nil {
		return m.Chapters
	}
	return nil
}

func (m *GetChaptersByIdRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type AddChapterReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=BookId,proto3" json:"BookId,omitempty"`
	ChapterName          string   `protobuf:"bytes,2,opt,name=ChapterName,proto3" json:"ChapterName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddChapterReq) Reset()         { *m = AddChapterReq{} }
func (m *AddChapterReq) String() string { return proto.CompactTextString(m) }
func (*AddChapterReq) ProtoMessage()    {}
func (*AddChapterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{20}
}

func (m *AddChapterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddChapterReq.Unmarshal(m, b)
}
func (m *AddChapterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddChapterReq.Marshal(b, m, deterministic)
}
func (m *AddChapterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddChapterReq.Merge(m, src)
}
func (m *AddChapterReq) XXX_Size() int {
	return xxx_messageInfo_AddChapterReq.Size(m)
}
func (m *AddChapterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddChapterReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddChapterReq proto.InternalMessageInfo

func (m *AddChapterReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *AddChapterReq) GetChapterName() string {
	if m != nil {
		return m.ChapterName
	}
	return ""
}

type AddChapterRes struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Err                  string   `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddChapterRes) Reset()         { *m = AddChapterRes{} }
func (m *AddChapterRes) String() string { return proto.CompactTextString(m) }
func (*AddChapterRes) ProtoMessage()    {}
func (*AddChapterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{21}
}

func (m *AddChapterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddChapterRes.Unmarshal(m, b)
}
func (m *AddChapterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddChapterRes.Marshal(b, m, deterministic)
}
func (m *AddChapterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddChapterRes.Merge(m, src)
}
func (m *AddChapterRes) XXX_Size() int {
	return xxx_messageInfo_AddChapterRes.Size(m)
}
func (m *AddChapterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AddChapterRes.DiscardUnknown(m)
}

var xxx_messageInfo_AddChapterRes proto.InternalMessageInfo

func (m *AddChapterRes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AddChapterRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type EditChapterReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	ChapterId            int32    `protobuf:"varint,2,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	Field                string   `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditChapterReq) Reset()         { *m = EditChapterReq{} }
func (m *EditChapterReq) String() string { return proto.CompactTextString(m) }
func (*EditChapterReq) ProtoMessage()    {}
func (*EditChapterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{22}
}

func (m *EditChapterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditChapterReq.Unmarshal(m, b)
}
func (m *EditChapterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditChapterReq.Marshal(b, m, deterministic)
}
func (m *EditChapterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditChapterReq.Merge(m, src)
}
func (m *EditChapterReq) XXX_Size() int {
	return xxx_messageInfo_EditChapterReq.Size(m)
}
func (m *EditChapterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditChapterReq.DiscardUnknown(m)
}

var xxx_messageInfo_EditChapterReq proto.InternalMessageInfo

func (m *EditChapterReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *EditChapterReq) GetChapterId() int32 {
	if m != nil {
		return m.ChapterId
	}
	return 0
}

func (m *EditChapterReq) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *EditChapterReq) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type EditChapterRes struct {
	Err                  string   `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditChapterRes) Reset()         { *m = EditChapterRes{} }
func (m *EditChapterRes) String() string { return proto.CompactTextString(m) }
func (*EditChapterRes) ProtoMessage()    {}
func (*EditChapterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{23}
}

func (m *EditChapterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditChapterRes.Unmarshal(m, b)
}
func (m *EditChapterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditChapterRes.Marshal(b, m, deterministic)
}
func (m *EditChapterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditChapterRes.Merge(m, src)
}
func (m *EditChapterRes) XXX_Size() int {
	return xxx_messageInfo_EditChapterRes.Size(m)
}
func (m *EditChapterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EditChapterRes.DiscardUnknown(m)
}

var xxx_messageInfo_EditChapterRes proto.InternalMessageInfo

func (m *EditChapterRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type GetEditorCmdReq struct {
	BookId               int64    `protobuf:"varint,1,opt,name=bookId,proto3" json:"bookId,omitempty"`
	ChapterId            int32    `protobuf:"varint,2,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEditorCmdReq) Reset()         { *m = GetEditorCmdReq{} }
func (m *GetEditorCmdReq) String() string { return proto.CompactTextString(m) }
func (*GetEditorCmdReq) ProtoMessage()    {}
func (*GetEditorCmdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{24}
}

func (m *GetEditorCmdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEditorCmdReq.Unmarshal(m, b)
}
func (m *GetEditorCmdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEditorCmdReq.Marshal(b, m, deterministic)
}
func (m *GetEditorCmdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEditorCmdReq.Merge(m, src)
}
func (m *GetEditorCmdReq) XXX_Size() int {
	return xxx_messageInfo_GetEditorCmdReq.Size(m)
}
func (m *GetEditorCmdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEditorCmdReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetEditorCmdReq proto.InternalMessageInfo

func (m *GetEditorCmdReq) GetBookId() int64 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *GetEditorCmdReq) GetChapterId() int32 {
	if m != nil {
		return m.ChapterId
	}
	return 0
}

type GetEditorCmdRes struct {
	Cmd                  *AppEditorCmd `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Err                  string        `protobuf:"bytes,15,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetEditorCmdRes) Reset()         { *m = GetEditorCmdRes{} }
func (m *GetEditorCmdRes) String() string { return proto.CompactTextString(m) }
func (*GetEditorCmdRes) ProtoMessage()    {}
func (*GetEditorCmdRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d780504008e31fd, []int{25}
}

func (m *GetEditorCmdRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEditorCmdRes.Unmarshal(m, b)
}
func (m *GetEditorCmdRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEditorCmdRes.Marshal(b, m, deterministic)
}
func (m *GetEditorCmdRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEditorCmdRes.Merge(m, src)
}
func (m *GetEditorCmdRes) XXX_Size() int {
	return xxx_messageInfo_GetEditorCmdRes.Size(m)
}
func (m *GetEditorCmdRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEditorCmdRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetEditorCmdRes proto.InternalMessageInfo

func (m *GetEditorCmdRes) GetCmd() *AppEditorCmd {
	if m != nil {
		return m.Cmd
	}
	return nil
}

func (m *GetEditorCmdRes) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*AppUserInfo)(nil), "editorpb.AppUserInfo")
	proto.RegisterType((*EditProfileReq)(nil), "editorpb.EditProfileReq")
	proto.RegisterType((*EditProfileRes)(nil), "editorpb.EditProfileRes")
	proto.RegisterType((*AppEditorCharacter)(nil), "editorpb.AppEditorCharacter")
	proto.RegisterType((*AppEditorBook)(nil), "editorpb.AppEditorBook")
	proto.RegisterType((*AppEditorChapter)(nil), "editorpb.AppEditorChapter")
	proto.RegisterType((*EditorBook)(nil), "editorpb.EditorBook")
	proto.RegisterType((*AppEditorCmd)(nil), "editorpb.AppEditorCmd")
	proto.RegisterType((*CharactersReq)(nil), "editorpb.CharactersReq")
	proto.RegisterType((*CharactersRes)(nil), "editorpb.CharactersRes")
	proto.RegisterType((*AddCharacterReq)(nil), "editorpb.AddCharacterReq")
	proto.RegisterType((*AddCharacterRes)(nil), "editorpb.AddCharacterRes")
	proto.RegisterType((*DelCharacterReq)(nil), "editorpb.DelCharacterReq")
	proto.RegisterType((*DelCharacterRes)(nil), "editorpb.DelCharacterRes")
	proto.RegisterType((*EditCharacterReq)(nil), "editorpb.EditCharacterReq")
	proto.RegisterType((*EditCharacterRes)(nil), "editorpb.EditCharacterRes")
	proto.RegisterType((*GetBookByIdReq)(nil), "editorpb.GetBookByIdReq")
	proto.RegisterType((*GetBookByIdRes)(nil), "editorpb.GetBookByIdRes")
	proto.RegisterType((*GetChaptersByIdReq)(nil), "editorpb.GetChaptersByIdReq")
	proto.RegisterType((*GetChaptersByIdRes)(nil), "editorpb.GetChaptersByIdRes")
	proto.RegisterType((*AddChapterReq)(nil), "editorpb.AddChapterReq")
	proto.RegisterType((*AddChapterRes)(nil), "editorpb.AddChapterRes")
	proto.RegisterType((*EditChapterReq)(nil), "editorpb.EditChapterReq")
	proto.RegisterType((*EditChapterRes)(nil), "editorpb.EditChapterRes")
	proto.RegisterType((*GetEditorCmdReq)(nil), "editorpb.GetEditorCmdReq")
	proto.RegisterType((*GetEditorCmdRes)(nil), "editorpb.GetEditorCmdRes")
}

func init() { proto.RegisterFile("editor.proto", fileDescriptor_7d780504008e31fd) }

var fileDescriptor_7d780504008e31fd = []byte{
	// 1019 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0x23, 0x45,
	0x10, 0xc5, 0x97, 0xf1, 0xa5, 0x9c, 0xc4, 0xa1, 0x81, 0xd0, 0x8a, 0x22, 0x64, 0x0d, 0x2b, 0x61,
	0x09, 0x14, 0x20, 0x2b, 0xf1, 0x8c, 0x2f, 0xc1, 0x1a, 0x58, 0xb2, 0xd1, 0x84, 0x88, 0x37, 0xa4,
	0xc9, 0x74, 0xc7, 0x19, 0xc5, 0x73, 0xd9, 0x9e, 0x76, 0x84, 0x3f, 0x88, 0x9f, 0xe0, 0x37, 0x78,
	0xe5, 0x89, 0x2f, 0x41, 0xd5, 0xdd, 0x73, 0xb3, 0x27, 0xd9, 0x6c, 0x9e, 0xd2, 0xa7, 0xba, 0xa6,
	0x2e, 0xa7, 0x4f, 0x95, 0x03, 0x7b, 0x9c, 0x05, 0x32, 0x16, 0xa7, 0x89, 0x88, 0x65, 0x4c, 0x7a,
	0x1a, 0x25, 0x37, 0xf6, 0x3f, 0x2d, 0x18, 0x4c, 0x92, 0xe4, 0x3a, 0xe5, 0xc2, 0x89, 0x6e, 0x63,
	0x72, 0x00, 0x4d, 0x67, 0x4e, 0x1b, 0xa3, 0xc6, 0xb8, 0xe5, 0x36, 0x9d, 0x39, 0x39, 0x82, 0x8e,
	0xba, 0x9b, 0xd3, 0xa6, 0xb2, 0x19, 0x44, 0x8e, 0xa1, 0x77, 0x11, 0xf8, 0xf7, 0x17, 0x5e, 0xc8,
	0x69, 0x6b, 0xd4, 0x18, 0xf7, 0xdd, 0x1c, 0x13, 0x02, 0xed, 0x39, 0x4f, 0x7d, 0xda, 0x56, 0x76,
	0x75, 0x26, 0x9f, 0x82, 0x75, 0x1e, 0x7a, 0xc1, 0x8a, 0x5a, 0xca, 0xa8, 0x01, 0x46, 0x5f, 0xf0,
	0x88, 0x71, 0x41, 0x3b, 0xa3, 0xc6, 0xd8, 0x72, 0x0d, 0x22, 0x87, 0xd0, 0x9a, 0x2c, 0x39, 0xed,
	0x2a, 0x23, 0x1e, 0xd1, 0x73, 0xf2, 0xe0, 0x49, 0x4f, 0xd0, 0x9e, 0x0a, 0x60, 0x10, 0xc6, 0x9d,
	0x2e, 0x9d, 0x70, 0x49, 0xfb, 0x3a, 0xae, 0x02, 0xe4, 0x04, 0xfa, 0x57, 0xc1, 0x32, 0xf2, 0xe4,
	0x5a, 0x70, 0x0a, 0xea, 0xa6, 0x30, 0x60, 0xed, 0xd3, 0x40, 0xc8, 0x3b, 0xe6, 0x6d, 0xe8, 0x40,
	0xd7, 0x9e, 0x61, 0xcc, 0x73, 0xe1, 0xc9, 0x20, 0x8e, 0xe8, 0x9e, 0xce, 0xa3, 0x11, 0x7e, 0x73,
	0x29, 0xe2, 0x87, 0x20, 0xf2, 0x39, 0xdd, 0xd7, 0xdf, 0x64, 0x18, 0xfb, 0x9d, 0x05, 0x72, 0x43,
	0x0f, 0x74, 0xbf, 0x78, 0xc6, 0x38, 0xb3, 0x78, 0x1d, 0xc9, 0x0d, 0x1d, 0xea, 0x38, 0x1a, 0x61,
	0x9c, 0x37, 0xb1, 0xaf, 0x33, 0x1c, 0xea, 0x38, 0x19, 0xc6, 0x5e, 0x5c, 0xbe, 0x74, 0x2e, 0xe9,
	0xc7, 0xaa, 0x6f, 0x0d, 0x08, 0x85, 0xee, 0x4c, 0x70, 0x4f, 0x72, 0x46, 0x89, 0xb2, 0x67, 0x10,
	0x6f, 0xae, 0x13, 0xa6, 0x6e, 0x3e, 0xd1, 0x37, 0x06, 0xda, 0xf7, 0x70, 0x70, 0xce, 0x02, 0x79,
	0x29, 0xe2, 0xdb, 0x60, 0xc5, 0x5d, 0xfe, 0x0e, 0x19, 0xbd, 0x0e, 0x98, 0x79, 0x58, 0x3c, 0x62,
	0x85, 0x3f, 0x05, 0x7c, 0xc5, 0x52, 0xda, 0x1c, 0xb5, 0xb0, 0x42, 0x8d, 0xc8, 0xb7, 0xd0, 0x35,
	0xdf, 0xa9, 0x87, 0x1d, 0x9c, 0x7d, 0x76, 0x9a, 0xa9, 0xe5, 0xb4, 0xa4, 0x14, 0x37, 0xf3, 0xb2,
	0xed, 0xad, 0x64, 0x29, 0x26, 0x3b, 0x17, 0x42, 0x25, 0xeb, 0xbb, 0x78, 0xb4, 0xff, 0x6d, 0x00,
	0x99, 0x24, 0xc9, 0xb9, 0x0a, 0x34, 0xbb, 0xf3, 0x84, 0xe7, 0x4b, 0x2e, 0x94, 0xda, 0x74, 0x51,
	0x96, 0xdb, 0x74, 0x54, 0x4d, 0xd3, 0x38, 0xbe, 0x77, 0x58, 0xa6, 0x36, 0x8d, 0x9e, 0x54, 0xdb,
	0x2b, 0xd8, 0xcf, 0x03, 0xfe, 0xb6, 0x49, 0xb8, 0x92, 0x9d, 0xe5, 0x56, 0x8d, 0xc8, 0xed, 0x64,
	0x15, 0x2c, 0xa3, 0x4c, 0x7f, 0x0a, 0xe0, 0xcb, 0x39, 0x7e, 0x1c, 0x29, 0xf5, 0xf5, 0x5d, 0x75,
	0x2e, 0xf3, 0xdd, 0x7d, 0x94, 0xef, 0x5e, 0x95, 0xef, 0xbf, 0x9a, 0xb0, 0x9f, 0xb7, 0x87, 0x35,
	0x97, 0xe6, 0xc8, 0x7a, 0x72, 0x8e, 0xb2, 0x8e, 0xe7, 0xaa, 0xaf, 0xac, 0xe3, 0x39, 0x56, 0xa6,
	0xba, 0x35, 0x33, 0x54, 0x99, 0x2b, 0xab, 0x34, 0x57, 0x47, 0xd0, 0x71, 0x42, 0x6f, 0xc9, 0x53,
	0xd3, 0x83, 0x41, 0xc4, 0x86, 0xbd, 0xb7, 0xd1, 0x2a, 0x88, 0xf8, 0x95, 0xf4, 0xe4, 0x3a, 0x35,
	0xad, 0x54, 0x6c, 0xe4, 0x0b, 0x80, 0xdf, 0x63, 0x71, 0x6f, 0x3c, 0x74, 0x4b, 0x25, 0x0b, 0x4e,
	0xd1, 0x64, 0x2d, 0xef, 0x62, 0x71, 0xb1, 0x0e, 0xd5, 0x7c, 0x59, 0x6e, 0x61, 0x28, 0xf3, 0x04,
	0x8f, 0xf2, 0x34, 0xa8, 0xf2, 0xf4, 0x5f, 0x03, 0x0e, 0xcb, 0x32, 0x48, 0x32, 0x11, 0x6c, 0x51,
	0x65, 0x28, 0x69, 0xd6, 0x52, 0xd2, 0x2a, 0x51, 0x72, 0x0c, 0xbd, 0x59, 0xc8, 0xd4, 0x6c, 0x99,
	0x77, 0xcf, 0xb1, 0x69, 0x8f, 0xa5, 0xfa, 0xd6, 0xca, 0xdb, 0x33, 0x96, 0x1d, 0x8a, 0x3a, 0x35,
	0x14, 0xbd, 0x44, 0x0c, 0xef, 0x00, 0x4a, 0x42, 0xf8, 0x1a, 0xda, 0xf8, 0x57, 0xf5, 0x37, 0x38,
	0xfb, 0xbc, 0x32, 0x4b, 0x85, 0x9b, 0xab, 0x9c, 0xc8, 0x0f, 0xd0, 0x33, 0xac, 0xe8, 0xa9, 0x1c,
	0x9c, 0x1d, 0xd7, 0x7c, 0x60, 0x5c, 0xdc, 0xdc, 0xd7, 0xfe, 0xbb, 0x01, 0x7b, 0xc5, 0x75, 0xc8,
	0x9e, 0xcd, 0x69, 0x21, 0xcb, 0x56, 0x45, 0x96, 0x27, 0xd0, 0x37, 0xc1, 0x9d, 0xb9, 0x21, 0xb6,
	0x30, 0x28, 0x56, 0x42, 0xf6, 0x26, 0x48, 0xa5, 0xd1, 0x62, 0x06, 0xcb, 0x7c, 0x75, 0x1e, 0xe5,
	0xab, 0x5b, 0xe5, 0xeb, 0xab, 0xd2, 0x00, 0xa7, 0xb8, 0xab, 0x8e, 0xa0, 0x73, 0xa3, 0xb7, 0x80,
	0x5e, 0x57, 0x06, 0xd9, 0x57, 0x55, 0xc7, 0x94, 0x7c, 0x07, 0x6d, 0xe6, 0x49, 0x8f, 0x36, 0x14,
	0x55, 0x27, 0xf5, 0x54, 0x69, 0x7f, 0x57, 0x79, 0xe2, 0x66, 0xe2, 0x42, 0x98, 0x9d, 0x8c, 0x47,
	0x7b, 0x09, 0xc3, 0x09, 0x63, 0x85, 0x9f, 0xce, 0x3f, 0xad, 0xe4, 0x37, 0x5b, 0x28, 0x13, 0x60,
	0xb3, 0x3a, 0x93, 0x6a, 0x83, 0xb4, 0x4a, 0x1b, 0x24, 0xdf, 0x35, 0xed, 0xd2, 0xae, 0xb1, 0x5f,
	0x6f, 0x27, 0x4a, 0x77, 0xd6, 0x9f, 0xd9, 0x9b, 0xc3, 0x62, 0x6f, 0xfe, 0x02, 0xc3, 0x39, 0x5f,
	0x3d, 0xab, 0xba, 0x11, 0x0c, 0x72, 0x3f, 0xb3, 0x40, 0x2d, 0xb7, 0x6c, 0xb2, 0xbf, 0xdc, 0x0e,
	0x96, 0xd6, 0x64, 0xfc, 0x13, 0x0e, 0x91, 0xba, 0xed, 0x94, 0x75, 0x0f, 0x82, 0x29, 0xfd, 0xdd,
	0x94, 0x25, 0x13, 0x52, 0x71, 0x8b, 0x3f, 0x2b, 0x86, 0x1f, 0x0d, 0xd0, 0xfa, 0xe0, 0xad, 0xd6,
	0xd9, 0x76, 0xd3, 0xc0, 0x7e, 0xb5, 0x93, 0x39, 0xad, 0x79, 0xaf, 0x31, 0x1c, 0x2c, 0xb8, 0xc4,
	0x9e, 0xa7, 0x1b, 0x87, 0x3d, 0x41, 0x88, 0xfd, 0x76, 0xcb, 0x33, 0xc5, 0x59, 0xbc, 0x79, 0xce,
	0x2c, 0xa2, 0x53, 0x4d, 0xea, 0x6f, 0x80, 0x2c, 0xb8, 0xcc, 0x86, 0xee, 0x7d, 0xe9, 0xff, 0xa8,
	0xf1, 0x4e, 0x71, 0xc2, 0xfd, 0x6c, 0xc2, 0x1b, 0xef, 0x9f, 0xf0, 0xcc, 0x37, 0xab, 0xa6, 0x59,
	0x54, 0xe3, 0xc0, 0xbe, 0xd6, 0x53, 0xf2, 0x2c, 0x61, 0xa0, 0x57, 0x49, 0xbd, 0x65, 0x93, 0xfd,
	0x7d, 0x35, 0x94, 0x12, 0x66, 0x90, 0x0b, 0x33, 0x60, 0x35, 0x5c, 0x08, 0xfd, 0xa3, 0x5f, 0x4d,
	0x5f, 0x2b, 0x92, 0x13, 0xe8, 0x9b, 0x2e, 0x72, 0x89, 0x14, 0x86, 0x0f, 0x12, 0x88, 0xbd, 0x95,
	0xb3, 0x4e, 0x1e, 0x0b, 0x18, 0x2e, 0xb8, 0xcc, 0x17, 0xe1, 0x8b, 0x0b, 0xb3, 0x7f, 0xdd, 0x0e,
	0x94, 0x92, 0x31, 0xb4, 0xfc, 0x90, 0x19, 0xf5, 0x1c, 0xd5, 0x3d, 0x5b, 0xc8, 0x5c, 0x74, 0xd9,
	0xad, 0xeb, 0xec, 0x67, 0xe8, 0x68, 0x1f, 0xf2, 0x23, 0x40, 0xb1, 0xc5, 0x48, 0x49, 0x84, 0x95,
	0x25, 0x78, 0xfc, 0xc8, 0x45, 0x6a, 0x7f, 0x74, 0xd3, 0x51, 0xff, 0xc4, 0xbf, 0xfe, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0xbc, 0x16, 0x7b, 0x50, 0xd4, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EditorClient is the client API for Editor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EditorClient interface {
	Characters(ctx context.Context, in *CharactersReq, opts ...grpc.CallOption) (*CharactersRes, error)
}

type editorClient struct {
	cc *grpc.ClientConn
}

func NewEditorClient(cc *grpc.ClientConn) EditorClient {
	return &editorClient{cc}
}

func (c *editorClient) Characters(ctx context.Context, in *CharactersReq, opts ...grpc.CallOption) (*CharactersRes, error) {
	out := new(CharactersRes)
	err := c.cc.Invoke(ctx, "/editorpb.Editor/Characters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EditorServer is the server API for Editor service.
type EditorServer interface {
	Characters(context.Context, *CharactersReq) (*CharactersRes, error)
}

// UnimplementedEditorServer can be embedded to have forward compatible implementations.
type UnimplementedEditorServer struct {
}

func (*UnimplementedEditorServer) Characters(ctx context.Context, req *CharactersReq) (*CharactersRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Characters not implemented")
}

func RegisterEditorServer(s *grpc.Server, srv EditorServer) {
	s.RegisterService(&_Editor_serviceDesc, srv)
}

func _Editor_Characters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CharactersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditorServer).Characters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/editorpb.Editor/Characters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditorServer).Characters(ctx, req.(*CharactersReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Editor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "editorpb.Editor",
	HandlerType: (*EditorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Characters",
			Handler:    _Editor_Characters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "editor.proto",
}
