---
system_name: data_anas
instance_id: data_anas_1
server_host: localhost:8080
debug: true
mysql_db_args:
  url: "test:123456@tcp(192.168.10.166:3306)/ez_go_example?charset=utf8&collation=utf8_general_ci&readTimeout=60s&timeout=30s&writeTimeout=30s"
  conn_max_lift_time: 30
  max_idle_conns: 100
  max_open_conns: 200  

task_configs: 
 - { host: "192.168.10.166:61613", destination: "/queue/sys_event_recr", Workers: 5, error_destination: "/queue/sys_event_recr_error",  consumer_mode: 2}
 - { host: "192.168.10.166:61613", destination: "/queue/sys_attr_recr", Workers: 5, error_destination: "/queue/sys_attr_recr_error",  consumer_mode: 2}
 - { host: "192.168.10.166:61613", destination: "/queue/sys_intra_data_anas_recr", Workers: 5, error_destination: "/queue/sys_intra_data_anas_recr_error",  consumer_mode: 1}
 - { host: "192.168.10.166:61613", destination: "/topic/sys_intra_data_anas_recr", Workers: 3, error_destination: "/queue/sys_intra_data_anas_recr_error",  consumer_mode: 1}
 - { host: "192.168.10.166:61613", destination: "/queue/sys_service_recr", Workers: 5, error_destination: "/queue/sys_service_recr_error",  consumer_mode: 1}
 - { host: "192.168.10.166:61613", destination: "/queue/home_recr", Workers: 5, error_destination: "/queue/home_recr_error",  consumer_mode: 1}


intra_mq_host: 192.168.10.166:61613
msgpush_mq_host: 192.168.10.166:61613


mongodb_url: mongodb://192.168.10.108:27017?maxPoolSize=10 #[mongodb://][user:pass@]host1[:port1][,host2[:port2],...][/database][?options]  e.g:mongodb://myuser:mypass@localhost:40001,otherhost:40001/mydb
#内部接口
api_host:
  url: "http://api.1719.com"
  key: "EA745B4FD18BC9870A5E956B4CBDE1A1"
  salt: "A18C721BE2756099049F4329834AFE30"

#本系统提供的http接口访问密钥
service_secret_key:
  "EA745B4FD18BC9870A5E956B4CBDE1A1": A18C721BE2756099049F4329834AFE30
  
memcache_server: 
 - 192.168.10.166:11211

redis_server: 
  addrs:   # Redis集群的服务器信息
    - 192.168.10.108:6380
    - 192.168.10.108:6381
    - 192.168.10.108:6382
    - 192.168.10.166:6383
    - 192.168.10.166:6384
    - 192.168.10.166:6385
  password:  # 服务密码，可选参数
  max_redirects: 16  # 最大重定向次数
  read_only: true # 启用读请求到从节点
  route_by_latency: true  # 路由读请求到最近节点或从节点， Enables routing read-only queries to the closest master or slave node.
  dial_timeout: 10000 # 建立连接的超时时长，以毫秒为单位
  read_timeout: 30000 # 读请求超时时长，以毫秒为单位
  write_timeout: 30000 # 写请求超时时长，以毫秒为单位
  pool_size: 10  # 每个集群的连接池大小
  pool_timeout: 35000 # 当连接池中所有连接都被使用时，获取连接请求的等待时长，超过此时长则返回一个错误，以毫秒为单位
  idle_timeout: 600 # 空闲连接的超时时长，必须小于服务端的timeout配置参数，超过此时长则关闭空闲连接，以秒为单位
  idle_check_frequency: 60 # 空闲连接的检测频率，以秒为单位，设置为负数则不检查
  
scribe_config:
  host: "192.168.10.166"
  port: "1463"
  queue_size: 2 
 
device_offline_timeout: 900000 #设备离线超时时间以微秒为单位 15分钟

staticserver_host: "http://static.1719.com"
etcd_server: #etcd服务配置
 endpoints:
  - "http://192.168.10.166:22379"
  - "http://192.168.10.166:2379"
  - "http://192.168.10.166:32379"
 dial_timeout: 5 #超时时间秒为单位
 user_name: "root"
 password: "12345678"

  
  
