// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	EmptyRes
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyRes struct {
}

func (m *EmptyRes) Reset()                    { *m = EmptyRes{} }
func (m *EmptyRes) String() string            { return proto.CompactTextString(m) }
func (*EmptyRes) ProtoMessage()               {}
func (*EmptyRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*EmptyRes)(nil), "pb.EmptyRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	SaveBank(ctx context.Context, in *EmptyRes, opts ...grpc.CallOption) (*EmptyRes, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) SaveBank(ctx context.Context, in *EmptyRes, opts ...grpc.CallOption) (*EmptyRes, error) {
	out := new(EmptyRes)
	err := grpc.Invoke(ctx, "/pb.User/SaveBank", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	SaveBank(context.Context, *EmptyRes) (*EmptyRes, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_SaveBank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).SaveBank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.User/SaveBank",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).SaveBank(ctx, req.(*EmptyRes))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveBank",
			Handler:    _User_SaveBank_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 93 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xe2, 0xe2,
	0xe2, 0x70, 0xcd, 0x2d, 0x28, 0xa9, 0x0c, 0x4a, 0x2d, 0x36, 0x32, 0xe0, 0x62, 0x09, 0x2d, 0x4e,
	0x2d, 0x12, 0xd2, 0xe0, 0xe2, 0x08, 0x4e, 0x2c, 0x4b, 0x75, 0x4a, 0xcc, 0xcb, 0x16, 0xe2, 0xd1,
	0x2b, 0x48, 0xd2, 0x83, 0xa9, 0x90, 0x42, 0xe1, 0x29, 0x31, 0x24, 0xb1, 0x81, 0x0d, 0x32, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xcb, 0x08, 0x6e, 0x59, 0x00, 0x00, 0x00,
}
